module.exports = {
    UNSPECIFIED: "PLATFORM_UNSPECIFIED",
    FACEBOOK: "FACEBOOK",
    SLACK: "SLACK",
    TELEGRAM: "TELEGRAM",
    KIK: "KIK",
    SKYPE: "SKYPE",
    LINE: "LINE",
    VIBER: "VIBER",
    ACTIONSONGOOGLE: "ACTIONS_ON_GOOGLE"
}